import React from 'react';

import { TimetableRow } from './TimetableRow/TimetableRow';

export function Timetable(): JSX.Element {
  return (
    <div className={`timetable`}>
      <TimetableRow
        isHeader
        cellData={[
          'Companies',
          '10:00',
          '10:30',
          '11:00',
          '11:30',
          '12:00',
          '12:30',
          '1:00',
          '1:30',
          '2:00',
          '2:30',
          '3:00',
          '3:30',
          '4:00',
        ]}
      />
      <TimetableRow
        cellData={[
          'AEM Creations',
          'X',
          'O',
          'X',
          'O',
          'O',
          'O',
          'O',
          'O',
          'X',
          'X',
          'X',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'App Lovin',
          'O',
          'O',
          'O',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'X',
        ]}
      />
      <TimetableRow
        cellData={[
          'Credera',
          'X',
          'X',
          'O',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
          'X',
          'X',
          'X',
        ]}
      />
      <TimetableRow
        cellData={[
          'Disney',
          'O',
          'X',
          'O',
          'O',
          'X',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'EA',
          'X',
          'X',
          'O',
          'O',
          'O',
          'X',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'IMG Studio',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'Might Coconut',
          'X',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
          'X',
          'O',
          'O',
          'O',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'Texas Film Commission',
          'O',
          'O',
          'O',
          'O',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'Texas Moving Picture Alliance (TXMPA)',
          'O',
          'O',
          'X',
          'O',
          'O',
          'O',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'Viasat',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'X',
          'O',
          'X',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'VIBE',
          'O',
          'O',
          'O',
          'O',
          'X',
          'O',
          'O',
          'O',
          'X',
          'O',
          'O',
          'O',
        ]}
      />
      <TimetableRow
        cellData={[
          'Vytal Studios',
          'O',
          'X',
          'X',
          'X',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
          'O',
        ]}
      />
    </div>
  );
}
