// generated by parseCompaniesCsv.js
export const data = JSON.parse(`[
  {
    "companyName": "Brazen Animation",
    "focuses": "Animation, Graphic Design",
    "positionTypes": [
      "Full-time Employees",
      "Contract Workers",
      "Freelancers"
    ],
    "website": "https://www.brazenanimation.com/",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "10:00-10:30, 10:30-11:00, 11:00-11:30, 11:30-12:00",
    "logoUrlCheckString": ""
  },
  {
    "companyName": "Texas Film Commission",
    "focuses": "Animation, Game Development",
    "positionTypes": [
      "Interns"
    ],
    "website": "www.gov.texas.gov/film",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/TFCLogo_Full.png?id=LDXaEG&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkxEWGFFRyIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.NzXUmpHtmsJECWibrlyfqaROrwS1sAYvs30Pf-lJwPQ&signature=26701a2f851751b403b2cc6e7fe444ced3fcbeebf475c2565b67922d1c08914d"
  },
  {
    "companyName": "A Bunch of Short Guys",
    "focuses": "Animation, Game Development, Graphic Design",
    "positionTypes": [
      "Volunteers",
      "Members"
    ],
    "website": "https://www.abunchofshortguys.org/",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/abosg.jpg?id=WJYkGL&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IldKWWtHTCIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.g6lNTeQCGt3hdMlttfQn10H1Jvfkom8hfWQDP8J0GBU&signature=47654fbe72cb7b2d0f4f8a8682c3d6e0282b4ec6482ea974072d2755b630b5dc"
  },
  {
    "companyName": "Luna Creative",
    "focuses": "Graphic Design",
    "positionTypes": [
      "Interns"
    ],
    "website": "www.luna-creative.com",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Luna_cREATIVE_4.jpg?id=xVP0b9&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhWUDBiOSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.Pu3Ux2vxQTfiSy8MaNZmjPivJAvyyVQA4DyQQ6t9oZo&signature=b72b0cc3a996c593ae0e892dc7ca52a4ec8c96034cdb46fae17ee48a58d8a61f"
  },
  {
    "companyName": "Framestore",
    "focuses": "Visual Effects, Animation, Immersive",
    "positionTypes": [
      "Interns",
      "Full-time Employees",
      "Part-Time Employees"
    ],
    "website": "https://www.framestore.com/about-us?language=en",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Copy-of-ICON_dblue.png?id=YjJ8Gq&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IllqSjhHcSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.EB-53nqu-ZpNiUINGL2T2GgEPgzo2lTJ29droOB_gls&signature=20d874e1514db159551e1f673b690975d2645d55815f907de828f0f9871717f5"
  },
  {
    "companyName": "POWER Engineers",
    "focuses": "VR/AR Engineering Visualization",
    "positionTypes": [
      "Interns",
      "Full-time Employees"
    ],
    "website": "powereng.com",
    "interviews": "Yes",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Logo.png?id=PRN5dd&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBSTjVkZCIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.xGUGbPDmNDptW4u3U6_HctLAhn-4dBM1zBgTjuMsDv4&signature=e95615acbc0079136266ec55a7343aec40d769829bef0b3909d5ee7adf89c57d"
  },
  {
    "companyName": "Overland Partners",
    "focuses": "architectural viz",
    "positionTypes": [
      "Full-time Employees",
      "Freelancers"
    ],
    "website": "www.overlandpartners.com",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "",
    "logoUrlCheckString": "https://storage.tally.so/private/final_logo_grey.png?id=gb2WdJ&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImdiMldkSiIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMTM3NzcwNH0.oLA1m-K7mfq14d2ntMZffdYCYYiC-O24A_fWj3Gradk&signature=3dc5935e8df1124528a8195645ac96789f9aec6ca2f98b323505aa1549664e1d"
  },
  {
    "companyName": "AEM Creations",
    "focuses": "Animation, Web Development, 3D Game Support",
    "positionTypes": [
      "Interns",
      "Contract Workers",
      "Freelancers"
    ],
    "website": "https://www.aem2create.com/",
    "interviews": "No",
    "virtualTimes": "All Day",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Logo_Full_Black.png?id=NqkMPQ&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik5xa01QUSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMTM4MjE3NH0.19Yh8uOKO6_EFb60PGCGcro4Pyjx0CY3rDcG24tM-5Q&signature=b469c4b44ac3302f89440c866cccf8478461ea080f9e00641f72d1629eafd699"
  }
]`);
