// generated by parseCompaniesCsv.js
export const data = JSON.parse(`[
  {
    "companyName": "Brazen Animation",
    "focuses": "Animation, Graphic Design",
    "positionTypes": [
      "Full-time Employees",
      "Contract Workers",
      "Freelancers"
    ],
    "website": "https://www.brazenanimation.com/",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "10:00-10:30, 10:30-11:00, 11:00-11:30, 11:30-12:00",
    "logoUrlCheckString": ""
  },
  {
    "companyName": "Texas Film Commission",
    "focuses": "Animation, Game Development",
    "positionTypes": [
      "Interns"
    ],
    "website": "www.gov.texas.gov/film",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/TFCLogo_Full.png?id=LDXaEG&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkxEWGFFRyIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.NzXUmpHtmsJECWibrlyfqaROrwS1sAYvs30Pf-lJwPQ&signature=26701a2f851751b403b2cc6e7fe444ced3fcbeebf475c2565b67922d1c08914d"
  },
  {
    "companyName": "A Bunch of Short Guys",
    "focuses": "Animation, Game Development, Graphic Design",
    "positionTypes": [
      "Volunteers",
      "Members"
    ],
    "website": "https://www.abunchofshortguys.org/",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/abosg.jpg?id=WJYkGL&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IldKWWtHTCIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.g6lNTeQCGt3hdMlttfQn10H1Jvfkom8hfWQDP8J0GBU&signature=47654fbe72cb7b2d0f4f8a8682c3d6e0282b4ec6482ea974072d2755b630b5dc"
  },
  {
    "companyName": "Luna Creative",
    "focuses": "Graphic Design",
    "positionTypes": [
      "Interns"
    ],
    "website": "www.luna-creative.com",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Luna_cREATIVE_4.jpg?id=xVP0b9&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhWUDBiOSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.Pu3Ux2vxQTfiSy8MaNZmjPivJAvyyVQA4DyQQ6t9oZo&signature=b72b0cc3a996c593ae0e892dc7ca52a4ec8c96034cdb46fae17ee48a58d8a61f"
  },
  {
    "companyName": "Framestore",
    "focuses": "Visual Effects, Animation, Immersive",
    "positionTypes": [
      "Interns",
      "Full-time Employees",
      "Part-Time Employees"
    ],
    "website": "https://www.framestore.com/about-us?language=en",
    "interviews": "No",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Copy-of-ICON_dblue.png?id=YjJ8Gq&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IllqSjhHcSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.EB-53nqu-ZpNiUINGL2T2GgEPgzo2lTJ29droOB_gls&signature=20d874e1514db159551e1f673b690975d2645d55815f907de828f0f9871717f5"
  },
  {
    "companyName": "POWER Engineers",
    "focuses": "VR/AR Engineering Visualization",
    "positionTypes": [
      "Interns",
      "Full-time Employees"
    ],
    "website": "powereng.com",
    "interviews": "Yes",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Logo.png?id=PRN5dd&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBSTjVkZCIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMDU4ODY1Nn0.xGUGbPDmNDptW4u3U6_HctLAhn-4dBM1zBgTjuMsDv4&signature=e95615acbc0079136266ec55a7343aec40d769829bef0b3909d5ee7adf89c57d"
  },
  {
    "companyName": "AEM Creations",
    "focuses": "Animation, Web Development, 3D Game Support",
    "positionTypes": [
      "Interns",
      "Contract Workers",
      "Freelancers"
    ],
    "website": "https://www.aem2create.com/",
    "interviews": "No",
    "virtualTimes": "All Day",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Logo_Full_Black.png?id=NqkMPQ&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik5xa01QUSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMTM4MjE3NH0.19Yh8uOKO6_EFb60PGCGcro4Pyjx0CY3rDcG24tM-5Q&signature=b469c4b44ac3302f89440c866cccf8478461ea080f9e00641f72d1629eafd699"
  },
  {
    "companyName": "Jacobs",
    "focuses": "AEC",
    "positionTypes": [
      "Full-time Employees",
      "Interns",
      "Contract Workers"
    ],
    "website": "jacobs.com",
    "interviews": "Yes",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Jacobs_logo_tag_left_rgb_white.png?id=VGzZQE&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlZHelpRRSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMjk5NzEzN30.tdXJSuohUMr3XVkY6al-nw0HI1XsBxFaJuIIPnEF7iM&signature=bcdba6a8ffaf50490b64d5db90481d2a4dc200679862b41ef289e18b3afac212"
  },
  {
    "companyName": "Overland Partners",
    "focuses": "architectural viz",
    "positionTypes": [
      "Full-time Employees",
      "Freelancers"
    ],
    "website": "www.overlandpartners.com",
    "interviews": "Yes",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Overland-logo.jpg?id=Q17r0l&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlExN3IwbCIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwMjk5OTYzMn0.O0hj0hNUFEEcDLLf0cTkcKgfORdddvuCKh7VIESP0GE&signature=0fb5c93bfb9ad868a9931e567b86e75b45d835b9beab0f665a8d938647abdb2e"
  },
  {
    "companyName": "Bluepoint Games",
    "focuses": "Game Development",
    "positionTypes": [
      "Interns"
    ],
    "website": "https://www.bluepointgames.com/",
    "interviews": "Yes",
    "virtualTimes": "All Day",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Bluepoint_Games_logo.png?id=Rx2KO4&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlJ4MktPNCIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwNTk1MDA4Nn0.FKgR_fnld3gnNrsBk1_gLngvXUUmZZENJEhm3OVFa_c&signature=79d2a8417bb64d9ea5083ce8cf4bd388d5fdde266c4be31871692e2719a5e839"
  },
  {
    "companyName": "TRG",
    "focuses": "Graphic Design, Advertising",
    "positionTypes": [
      "Part-Time Employees",
      "Full-time Employees",
      "Interns",
      "Contract Workers",
      "Freelancers"
    ],
    "website": "https://trg.agency/",
    "interviews": "No",
    "virtualTimes": "10:00-10:30, 10:30-11:00, 11:00-11:30, 11:30-12:00, 1:30-2:00, 2:00-2:30",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/TRG-Logo.jpeg?id=Aza5ve&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkF6YTV2ZSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwNjA0MDQ0N30.MJTUUCswzTtshBb0ogs34kp8i8eXO1txeQz08TIVPnM&signature=5ab175b4c4006b0296e4aeb48ada81c001864b03d7834a4577ef3d5977b5455d"
  },
  {
    "companyName": "Populous",
    "focuses": "Graphic Design",
    "positionTypes": [
      "Full-time Employees"
    ],
    "website": "https://populous.com",
    "interviews": "Yes",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Populous.jfif?id=qLpje2&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InFMcGplMiIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwNjEzNjc3Nn0.N0OyPyQXYLkf5eyWsrrCepgl-pW33BA4WOKR_riUQgQ&signature=cc0ceb0aaf3e7312c950991fdb511f04a53d2bfa04b0ede55369bb572554d198"
  },
  {
    "companyName": "Electronic Arts",
    "focuses": "Game Development",
    "positionTypes": [
      "Interns",
      "Full-time Employees"
    ],
    "website": "www.ea.com",
    "interviews": "No",
    "virtualTimes": "All Day",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://storage.tally.so/private/Electronic_Arts_wordmark_RGB_whitebackground.png?id=VGBYba&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlZHQlliYSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwNjU2NzM0NH0.oXFMQilSUXYstlK6aF93SKp_ffekcask_0zlt_Fe7GA&signature=2d3ec9509df655d1b5cf47e87960eb5d79dbf2a5041cb9a8aa38619cfa961d0f, https://storage.tally.so/private/Electronic_Arts_wordmark_RGB.png?id=Nr9YbG&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik5yOVliRyIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwNjU2NzM0NH0.S7QzTXAs7XRcsuW-KUcL9wPH8MUh8gmBTjEfCFibJYU&signature=eb113e85e18786e2673e264a209e7d72b58fa2127ce5c15cd70678b7d5d747c1"
  },
  {
    "companyName": "Deloitte",
    "focuses": "Graphic Design, UX/UI",
    "positionTypes": [
      "Full-time Employees"
    ],
    "website": "https://www.deloitte.com/global/en.html",
    "interviews": "No",
    "virtualTimes": "1:00-1:30, 11:00-11:30, 11:30-12:00, 12:30-1:00, 1:30-2:00",
    "inPersonTimes": "",
    "logoUrlCheckString": "https://storage.tally.so/private/Deloitte_Logo.png?id=7qg8NA&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdxZzhOQSIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwNjYzNTkxNn0.elR0VqVZ9WpOXzXHy1N5Frza6VbbtD8wfhE47iJ6shU&signature=38f4a6568aef448be84c73fa7f12fd6bcdf21e81c3a0f31782983355ce921c15"
  },
  {
    "companyName": "PBK Architects",
    "focuses": "Architectural Vizualization",
    "positionTypes": [
      "Interns",
      "Full-time Employees"
    ],
    "website": "https://pbk.com/",
    "interviews": "Yes",
    "virtualTimes": "",
    "inPersonTimes": "11:00-11:30, 11:30-12:00, 12:30-1:00, 1:00-1:30, 2:00-2:30, 3:00-3:30, 3:30-4:00, 1:30-2:00",
    "logoUrlCheckString": "https://storage.tally.so/private/PBK-LOGO-Vector.svg?id=EKoVGX&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVLb1ZHWCIsImZvcm1JZCI6Im1KcFd5ZCIsImlhdCI6MTcwNzI2MjEzOH0.Y3jLdkVTBcJS4PiH1Jv8sts7vQjVgco17Ts67dDg-EY&signature=ba14a4167f8fe3be88320a2f1793bd821cd062cdd53eec5c6be5bebb49acd55f"
  }
]`);
